const {test}=require('node:test');const assert=require('node:assert/strict');
const {validate,migrate,action}=require('../desktop/themes.cjs');const presets=require('../desktop/theme-presets.json');
const memory=()=>{const map=new Map();return {get:(k,d)=>map.has(k)?structuredClone(map.get(k)):d,set:(k,v)=>map.set(k,structuredClone(v))};};
test('All built-in themes validate; built-in edits become independent custom themes',()=>{for(const p of presets){const t=validate(p);assert.match(t.id,/^custom-/);assert.notEqual(t.palette,p.palette);}});
test('Theme validation rejects CSS injection, non-local images, invalid fonts and oversized fields',()=>{for(const mutate of [t=>t.palette.accent='red;url(https://example.com)',t=>t.background.image='file:///C:/private.png',t=>t.background.image='data:image/png;base64,AAAA',t=>t.font='url(x)',t=>t.effects.blur=500,t=>t.name='x'.repeat(61)]){const t=structuredClone(presets[0]);mutate(t);assert.throws(()=>validate(t));}});
test('Legacy automatic schedule is resolved once, with midnight boundaries',()=>{for(const [p,h,id] of [[{theme:'warm'},22,'light'],[{theme:'cinema'},9,'navy'],[{theme:'auto',cinemaStart:19,cinemaEnd:7},19,'navy'],[{theme:'auto'},7,'light']]){const s=memory();s.set('preferences',p);migrate(s,h);assert.equal(s.get('preferences').activeThemeId,id);migrate(s,12);assert.equal(s.get('preferences').activeThemeId,id);assert.equal(s.get('preferences').theme,undefined);}});
test('Saving, replacing and deleting a custom theme preserves built-ins and falls back safely',async()=>{const s=memory();const t=await action(s,'save',presets[1],{});assert.equal(s.get('preferences').activeThemeId,t.id);await action(s,'save',{...t,name:'Changed'},{});assert.equal(s.get('themes').length,1);await action(s,'delete',t.id,{});assert.equal(s.get('preferences').activeThemeId,'navy');assert.deepEqual(s.get('themes'),[]);});
test('Theme file export/import is versioned and imports receive a new identity',async()=>{const fs=require('node:fs/promises'),path=require('node:path');const dir=path.resolve('.test-output/theme-files');await fs.mkdir(dir,{recursive:true});const file=path.join(dir,'roundtrip.astra-theme.json');const dialog={showSaveDialog:async()=>({filePath:file}),showOpenDialog:async()=>({filePaths:[file]})};const s=memory();const t=validate(presets[2]);await action(s,'export',t,{dialog});const imported=await action(s,'import',null,{dialog});assert.deepEqual(imported.palette,t.palette);assert.notEqual(imported.id,t.id);await fs.writeFile(file,JSON.stringify({version:100,theme:t}));await assert.rejects(action(s,'import',null,{dialog}),/version/);});
test('Saved image is copied to profile assets and exported as embedded image after source removal',async()=>{
 const fs=require('node:fs/promises'),path=require('node:path');const dir=path.resolve('.test-output/theme-assets-test');await fs.mkdir(dir,{recursive:true});const assetDirectory=path.join(dir,'assets');
 const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aV1sAAAAASUVORK5CYII=','base64');const t=structuredClone(presets[0]);t.background.image=`data:image/png;base64,${bytes.toString('base64')}`;
 const s=memory(),saved=await action(s,'save',t,{assetDirectory});assert.match(saved.background.image,/^theme-art:\/\/[a-f0-9]{64}\/$/);assert.deepEqual(await fs.readFile(path.join(assetDirectory,new URL(saved.background.image).hostname)),bytes);
 const file=path.join(dir,'image.astra-theme.json'),dialog={showSaveDialog:async()=>({filePath:file}),showOpenDialog:async()=>({filePaths:[file]})};await action(s,'export',saved,{dialog,assetDirectory});const imported=await action(s,'import',null,{dialog});assert.equal(imported.background.image,t.background.image);
 assert.throws(()=>validate({...t,background:{...t.background,image:'theme-art://../../private'}}));
});
