import {_electron as electron} from 'playwright';
import path from 'node:path';
import fs from 'node:fs/promises';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
const require=createRequire(import.meta.url);
const {Store}=require('../desktop/store.cjs'),{Library}=require('../desktop/library.cjs');
const output=path.resolve('.test-output'),root=path.join(output,'astra-integration-library');
const folder=path.join('Bleach','Concentrated Bleach');
await fs.mkdir(path.join(root,folder),{recursive:true});
await fs.mkdir(path.join(root,'Other'),{recursive:true});
for(const name of ['Episode 1','Episode 2','Episode 10'])await fs.copyFile(path.join(output,'fixture.avi'),path.join(root,folder,`${name}.avi`));
await fs.copyFile(path.join(output,'fixture.avi'),path.join(root,'Other','Other film.avi'));
const store=new Store(path.join(output,'astra-integration-profile'));
store.set('root',root);store.set('preferences',{theme:'warm',autoplay:false,textScale:125});
store.set(`queue:${root}`,[]);store.set(`location:${root}`,'');store.set(`collapsed:${root}`,{});
const library=new Library(store);await library.scan();
for(const item of library.items())store.save(root,{...item,hidden:false,position:0,duration:0,watched:false,lastWatched:null});
store.close();
const app=await electron.launch({args:['.','--test-session'],cwd:path.resolve('.'),env:{...process.env,ELECTRON_RUN_AS_NODE:undefined},timeout:30000});
const errors=[];
try{
 const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));
 await page.getByRole('button',{name:'Open folder Bleach',exact:true}).waitFor();
 await page.getByRole('button',{name:'Collapse Recently added'}).click();
 await page.getByRole('button',{name:'Expand Recently added'}).waitFor();
 await page.getByRole('button',{name:'Open folder Bleach',exact:true}).click();
 await page.getByRole('button',{name:'Open folder Concentrated Bleach'}).click();
 await page.getByRole('button',{name:'Play Episode 1',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Play Other film',exact:true}).count(),0);
 await page.screenshot({path:path.join(output,'astra-folders.png')});
 await page.getByRole('button',{name:'Queue Episode 2',exact:true}).click();
 await page.getByRole('button',{name:'Queue Episode 10',exact:true}).click();
 let snapshot=await page.evaluate(()=>window.astra.snapshot());
 const ids=Object.fromEntries(snapshot.items.map(i=>[i.title,i.id]));
 assert.deepEqual(snapshot.queue,[ids['Episode 2'],ids['Episode 10']]);
 await page.getByRole('button',{name:'Queue 2',exact:true}).click();
 await page.getByRole('button',{name:'Play queue',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.play-time')?.textContent?.includes('0:05'));
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 snapshot=await page.evaluate(()=>window.astra.snapshot());
 assert.equal(snapshot.playback.currentId,ids['Episode 2']);
 assert.deepEqual(snapshot.queue,[ids['Episode 10']]);
 assert.deepEqual(snapshot.upNext,[ids['Episode 1']]);
 await page.getByRole('button',{name:'Playback speed',exact:true}).click();
 await page.getByRole('menuitemradio',{name:'1.5×',exact:true}).click();
 await page.getByRole('slider',{name:'Playback position'}).fill('1');
 await page.waitForFunction(async()=>Math.abs((await window.astra.snapshot()).player.position-1)<.2);
 const bounds=await page.evaluate(()=>{const v=document.querySelector('.astra-video-frame').getBoundingClientRect(),c=document.querySelector('.astra-controls').getBoundingClientRect();return {v:{bottom:v.bottom,width:v.width},c:{top:c.top,width:c.width,bottom:c.bottom},height:innerHeight};});
 assert.ok(bounds.v.bottom<=bounds.c.top+1);assert.ok(Math.abs(bounds.v.width-bounds.c.width)<1);assert.ok(bounds.c.bottom<=bounds.height);
 const slider=await page.getByRole('slider',{name:'Playback position'}).boundingBox();
 await page.mouse.move(slider.x+slider.width*.8,slider.y+slider.height/2);
 await page.getByRole('tooltip').waitFor();
 assert.equal(await page.getByRole('tooltip').textContent(),'0:04');
 await page.screenshot({path:path.join(output,'astra-watch.png')});
 await page.getByRole('button',{name:'Fullscreen',exact:true}).click();
 await page.waitForFunction(async()=>(await window.astra.snapshot()).playback.mode==='fullscreen');
 const controls=app.windows().find(p=>p.url().includes('surface=controls'));
 assert.ok(controls);controls.on('pageerror',e=>errors.push(e.message));
 await controls.evaluate(()=>window.astra.pinControls(true));
 await controls.getByRole('button',{name:'Exit fullscreen',exact:true}).waitFor();
 await controls.screenshot({path:path.join(output,'astra-fullscreen-controls.png')});
 const windows=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().map(w=>({id:w.id,parent:w.getParentWindow()?.id,url:w.webContents.getURL(),visible:w.isVisible()})));
 const overlay=windows.find(w=>w.url.includes('surface=controls'));
 assert.ok(windows.find(w=>w.id===overlay.parent)?.parent,'Controls are owned by the video surface, above it');
 await controls.getByRole('button',{name:'Exit fullscreen',exact:true}).click();
 await page.getByRole('button',{name:'Mini-player',exact:true}).click();
 await controls.evaluate(()=>window.astra.pinControls(true));
 await controls.getByRole('button',{name:'Restore player',exact:true}).waitFor();
 const handle=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>!w.webContents.getURL()).getNativeWindowHandle().readUInt32LE(0));
 console.log('Reset top',await app.evaluate(async({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>!w.webContents.getURL());const first=w.isAlwaysOnTop();w.setAlwaysOnTop(false);w.setAlwaysOnTop(true,'pop-up-menu');await new Promise(r=>setTimeout(r,300));return {first,second:w.isAlwaysOnTop()};}));
 console.log('Native style',spawnSync('powershell.exe',['-NoProfile','-Command',`Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public class AstraTest {[DllImport("user32.dll")] public static extern int GetWindowLong(IntPtr h,int n);}'; [AstraTest]::GetWindowLong([IntPtr]${handle},-20)`],{encoding:'utf8',windowsHide:true}).stdout);
 await page.evaluate(()=>window.astra.window('minimize'));
 const miniWindows=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().map(w=>({id:w.id,url:w.webContents.getURL(),parent:w.getParentWindow()?.id,top:w.isAlwaysOnTop(),visible:w.isVisible(),bounds:w.getBounds()})));
 assert.equal(miniWindows.find(w=>w.url==='')?.visible,true);
 console.log('After minimize',miniWindows);
 await controls.getByRole('button',{name:'Play',exact:true}).click();
 await controls.getByRole('button',{name:'Pause',exact:true}).click();
 await controls.evaluate(()=>window.astra.resizeMini({width:520,height:300}));
 await controls.screenshot({path:path.join(output,'astra-mini.png')});
 await controls.getByRole('button',{name:'Restore player',exact:true}).click();
 snapshot=await page.evaluate(()=>window.astra.snapshot());assert.equal(snapshot.player.speed,1.5);assert.ok(snapshot.player.position>=1);assert.equal(snapshot.player.paused,true);
 await page.getByRole('button',{name:'Play next',exact:true}).click();
 await page.waitForFunction(async()=>{const s=await window.astra.snapshot();return s.items.find(i=>i.id===s.playback.currentId)?.title==='Episode 10';});
 await page.getByRole('button',{name:'Stop video',exact:true}).click();
 await page.evaluate(()=>window.astra.browse('Bleach\\Concentrated Bleach'));
 await page.getByRole('button',{name:'Edit Episode 1',exact:true}).click();
 await page.getByRole('button',{name:'Hide from Astra',exact:true}).click();
 snapshot=await page.evaluate(()=>window.astra.snapshot());assert.equal(snapshot.items.find(i=>i.id===ids['Episode 1']).hidden,true);
 await fs.access(path.join(root,folder,'Episode 1.avi'));
 await page.getByRole('button',{name:'Undo',exact:true}).click();
 await page.evaluate(()=>window.astra.settings({textScale:200,theme:'cinema'}));
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('index.html')&&!w.webContents.getURL().includes('surface=controls')).setSize(960,640));
 await page.screenshot({path:path.join(output,'astra-200-percent.png')});
 await page.getByRole('navigation',{name:'Folder location'}).getByRole('button',{name:'Bleach',exact:true}).click();
 await page.getByRole('button',{name:'Open folder Concentrated Bleach'}).waitFor();
 assert.deepEqual(errors,[]);
 console.log('Desktop integration passed: folders, collapse, FIFO queue, folder suggestions, native playback, seek tooltip, speed, fullscreen ownership, independent mini-player, restore, hiding/undo, text scale, breadcrumbs.');
}finally{await app.close();}
