import {_electron as electron} from 'playwright';
import path from 'node:path';import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{Store}=require('../desktop/store.cjs');
const project=path.resolve(import.meta.dirname,'..'),output=path.join(project,'.test-output','theme-ui');await fs.mkdir(output,{recursive:true});
const s=new Store(path.join(output,'.test-output','astra-integration-profile'));s.set('preferences',{theme:'cinema',textScale:125});s.set('themes',[]);s.close();
const packaged=process.argv.includes('--packaged');
const launch=()=>electron.launch({...packaged?{executablePath:path.join(project,'release','win-unpacked','Astra.exe')}:{},args:[...(packaged?[]:[project]),'--test-session'],cwd:output,env:{...process.env,ELECTRON_RUN_AS_NODE:undefined}});
const imageFile=path.join(output,'background.png');await fs.writeFile(imageFile,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aV1sAAAAASUVORK5CYII=','base64'));
let app=await launch();
try{
 let page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.show();w.focus();});
 await page.waitForFunction(()=>document.documentElement.dataset.preset==='navy');
 assert.equal(await page.evaluate(()=>getComputedStyle(document.body).fontFamily.includes('Segoe UI')),true);
 await page.getByRole('button',{name:'Settings & preferences',exact:true}).click();
 for(const [name,id]of [['Light','light'],['Navy','navy'],['Frutiger Aero','aero']]){await page.getByRole('button',{name,exact:true}).click();await page.waitForFunction(id=>document.documentElement.dataset.preset===id,id);await page.waitForTimeout(450);await page.screenshot({path:path.join(output,`${id}.png`)});}
 await page.getByRole('button',{name:'Customize',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('My blue');await page.getByLabel('accent hex').fill('#3355bb');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal((await page.evaluate(()=>window.astra.snapshot())).themes.length,3);
 await page.getByRole('button',{name:'Customize',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('My blue');await page.getByLabel('accent hex').fill('#3355bb');await page.getByLabel('Font',{exact:true}).selectOption('Verdana');await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},imageFile);await page.getByRole('button',{name:'Choose local background image',exact:true}).click();await page.waitForTimeout(200);await page.getByRole('button',{name:'Save and apply',exact:true}).click();
 await page.getByRole('button',{name:'My blue',exact:true}).waitFor();const saved=await page.evaluate(()=>window.astra.snapshot());assert.equal(saved.themes.find(t=>t.id===saved.settings.activeThemeId).palette.accent,'#3355bb');
 const custom=saved.themes.find(t=>t.id===saved.settings.activeThemeId);assert.match(custom.background.image,/^theme-art:/);assert.equal(await page.evaluate(url=>new Promise(resolve=>{const image=new Image();image.onload=()=>resolve(true);image.onerror=()=>resolve(false);image.src=url;}),custom.background.image),true,'Copied background must load through the local image protocol');await fs.rm(imageFile);
 const exported=path.join(output,'exported.astra-theme.json');await fs.rm(exported,{force:true});await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},exported);await page.getByRole('button',{name:'Export theme',exact:true}).click();for(let n=0;n<50;n++){try{await fs.access(exported);break;}catch{await page.waitForTimeout(100);}}const doc=JSON.parse(await fs.readFile(exported,'utf8'));assert.equal(doc.version,1);assert.match(doc.theme.background.image,/^data:image/);await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},exported);await page.getByRole('button',{name:'Import theme',exact:true}).click();await page.getByLabel('Name',{exact:true}).waitFor();assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'My blue');await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('button',{name:'Playback',exact:true}).click();const toggle=page.getByRole('switch',{name:'Compatibility playback'});await toggle.focus();await toggle.press('Space');await page.waitForFunction(async()=>(await window.astra.snapshot()).settings.playbackCompatibility===true);
 await page.getByRole('button',{name:'Appearance',exact:true}).click();await page.getByRole('button',{name:'200%',exact:true}).click();await page.getByRole('button',{name:'Customize',exact:true}).click();await page.getByRole('button',{name:'Save and apply',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'editor-200.png')});await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await app.close();app=await launch();page=await app.firstWindow();await page.waitForFunction(id=>document.documentElement.dataset.preset===id,saved.settings.activeThemeId);assert.equal(await page.evaluate(()=>getComputedStyle(document.body).fontFamily.includes('Verdana')),true);
 await page.getByRole('button',{name:'Settings & preferences',exact:true}).click();await page.getByRole('button',{name:'Delete custom theme',exact:true}).click();await page.waitForFunction(()=>document.documentElement.dataset.preset==='navy');
 console.log(`${packaged?'Packaged':'Source'} theme UI passed: presets, custom save/cancel, font, copied background and local protocol, export/import, keyboard compatibility, 200% editor, persistence and deletion.`);
}finally{await app.close();}
