import {useState} from 'react';
import type {CSSProperties} from 'react';
import {api} from './state';
import {themeStyle,type Theme} from './theme';
import type {Settings,Snapshot} from './types';
const fonts=['Segoe UI Variable','Segoe UI','Arial','Verdana','Trebuchet MS'];
function contrast(a:string,b:string){const lum=(h:string)=>{const c=[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722;};const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
export function Appearance({data,change,run}:{data:Snapshot;change:(p:Partial<Settings>)=>unknown;run:<T>(work:()=>Promise<T>|undefined)=>Promise<T|undefined>}){
 const[draft,setDraft]=useState<Theme|null>(null);const active=data.themes.find(t=>t.id===data.settings.activeThemeId)||data.themes[0];
 const edit=(t:Theme,copy=false)=>setDraft(structuredClone({...t,id:copy||!t.id.startsWith('custom-')?'':t.id,name:copy||!t.id.startsWith('custom-')?`${t.name} copy`:t.name}));
 return <section><h3>Appearance</h3><p className="muted">Choose a theme manually. Your choice stays the same throughout the day.</p><div className="theme-options">{data.themes.map(t=><button key={t.id} aria-pressed={active.id===t.id} onClick={()=>change({activeThemeId:t.id})}>{t.name}</button>)}</div><div className="theme-actions"><button onClick={()=>edit(active)}>Customize</button><button onClick={()=>edit(active,true)}>Duplicate</button><button onClick={()=>run(async()=>{const t=await api?.theme('import');if(t)setDraft(t);})}>Import theme</button><button onClick={()=>run(()=>api?.theme('export',active))}>Export theme</button>{active.id.startsWith('custom-')&&<button onClick={()=>run(()=>api?.theme('delete',active.id))}>Delete custom theme</button>}</div>
 {draft&&<div className="theme-editor"><h3>Edit custom theme</h3><label>Name<input maxLength={60} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Colour scheme<select value={draft.scheme} onChange={e=>setDraft({...draft,scheme:e.target.value})}><option value="light">Light</option><option value="dark">Dark</option></select></label><label>Font<select aria-label="Font" value={draft.font} onChange={e=>setDraft({...draft,font:e.target.value})}>{fonts.map(f=><option key={f}>{f}</option>)}</select></label><label>Decoration<select aria-label="Decoration" value={draft.decoration||'none'} onChange={e=>setDraft({...draft,decoration:e.target.value})}><option value="none">None</option><option value="aero">Frutiger Aero sky and bubbles</option></select></label><div className="palette-grid">{Object.entries(draft.palette).map(([key,value])=><label key={key}>{key.replace(/([A-Z])/g,' $1')}<span><input aria-label={`${key} colour`} type="color" value={value} onChange={e=>setDraft({...draft,palette:{...draft.palette,[key]:e.target.value}})}/><input aria-label={`${key} hex`} value={value} maxLength={7} onChange={e=>setDraft({...draft,palette:{...draft.palette,[key]:e.target.value}})}/></span></label>)}</div>{(contrast(draft.palette.text,draft.palette.background)<4.5||contrast(draft.palette.buttonText,draft.palette.accent)<4.5)&&<p role="status">Some text colours have low contrast. Aim for at least 4.5:1 for comfortable reading.</p>}
 {(['opacity','blur','gloss','radius','shadow'] as const).map(key=><label key={key}>{key} {draft.effects[key]}<input type="range" min="0" max={key==='blur'||key==='radius'?40:100} value={draft.effects[key]} onChange={e=>setDraft({...draft,effects:{...draft.effects,[key]:Number(e.target.value)}})}/></label>)}<label><input type="checkbox" checked={draft.effects.motion} onChange={e=>setDraft({...draft,effects:{...draft.effects,motion:e.target.checked}})}/>Decorative motion (respects reduced motion)</label>
 <button onClick={()=>run(async()=>{const image=await api?.theme('image');if(image)setDraft({...draft,background:{...draft.background,image}});})}>Choose local background image</button><button onClick={()=>setDraft({...draft,background:{...draft.background,image:''}})}>Remove background</button><label>Image fit<select value={draft.background.fit} onChange={e=>setDraft({...draft,background:{...draft.background,fit:e.target.value}})}><option>cover</option><option>contain</option></select></label><label>Position<select value={draft.background.position} onChange={e=>setDraft({...draft,background:{...draft.background,position:e.target.value}})}>{['center','top','bottom','left','right'].map(v=><option key={v}>{v}</option>)}</select></label><label>Background dim {draft.background.dim}%<input type="range" min="0" max="100" value={draft.background.dim} onChange={e=>setDraft({...draft,background:{...draft.background,dim:Number(e.target.value)}})}/></label>
 <div className="theme-preview" style={themeStyle(draft) as CSSProperties}><h3>Your local cinema</h3><p>Preview your palette and typography.</p><button className="button primary">Play video</button><p className="muted">Secondary text and details</p></div><div className="theme-actions"><button className="button primary" onClick={()=>run(async()=>{await api?.theme('save',draft);setDraft(null);})}>Save and apply</button><button onClick={()=>setDraft(null)}>Cancel</button></div></div>}</section>;
}
