import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, CheckCheck, ChevronDown, Clapperboard, Clock3, Film, FolderOpen, GripVertical, House, ImagePlus, ListOrdered, Maximize, Minimize, Minus, Monitor, Moon, MoreHorizontal, Pause, Play, Plus, RefreshCw, Repeat, Search, Settings2, Shuffle, SkipForward, SlidersHorizontal, Sparkles, Square, Subtitles, Sun, Tv, Upload, Volume2, VolumeX, X } from 'lucide-react';
import type { Media, PlayerState, SelectedFile, Settings, Snapshot } from './types';
import './styles.css';
import './text-size.css';
import { version as appVersion } from '../package.json';

const initial: Snapshot = { root: '', items: [], queue: [], settings: { theme: 'auto', cinemaStart: 19, cinemaEnd: 7, autoplay: true, shuffle: false, repeat: 'off', volume: 80, speed: 1, textScale: 125 }, playerReady: false };
const initialPlayer: PlayerState = { position: 0, duration: 0, paused: true, volume: 80, speed: 1, tracks: [], loading: false };
const api = window.matinee;
const time = (seconds: number) => { const n = Math.floor(Math.max(0, seconds || 0)); return n >= 3600 ? `${Math.floor(n / 3600)}:${String(Math.floor(n / 60) % 60).padStart(2,'0')}:${String(n % 60).padStart(2,'0')}` : `${Math.floor(n / 60)}:${String(n % 60).padStart(2,'0')}`; };
const episodeSort = (a: Media, b: Media) => a.order != null || b.order != null ? (a.order ?? 1e9) - (b.order ?? 1e9) || a.title.localeCompare(b.title) : (a.season ?? 0) - (b.season ?? 0) || (a.episode ?? 0) - (b.episode ?? 0) || a.title.localeCompare(b.title, undefined, { numeric: true });
function seriesCards(items: Media[]) { const seen = new Set<string>(); return items.filter(item => { if (!item.series) return true; if (seen.has(item.series)) return false; seen.add(item.series); return true; }).map(item=>{if(!item.series)return item;const episodes=items.filter(i=>i.series===item.series).sort(episodeSort);return episodes.find(i=>!i.watched)??episodes[0];}); }
function suggested(items: Media[], current: Media | null, shuffle: boolean) {
  const eligible = items.filter(i => !i.missing && i.id !== current?.id);
  const episodes = current?.series ? eligible.filter(i => i.series === current.series && episodeSort(i,current) > 0).sort(episodeSort) : [];
  let others = seriesCards(eligible.filter(i => !i.watched && (!current?.series || i.series !== current.series))).sort((a,b) => Number(b.genre === current?.genre) - Number(a.genre === current?.genre));
  if (shuffle) { others = [...others]; for (let i = others.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i+1)); [others[i],others[j]] = [others[j],others[i]]; } }
  return [...episodes, ...others];
}
function IconButton({ label, children, onClick, active = false, disabled = false }: { label: string; children: React.ReactNode; onClick?: () => void; active?: boolean; disabled?: boolean }) { return <button className={`icon-button ${active ? 'active' : ''}`} title={label} aria-label={label} disabled={disabled} onClick={onClick}>{children}</button>; }
function Poster({ item, small = false }: { item: Media; small?: boolean }) {
  const [failed, setFailed] = useState(false);
  const hash = [...(item.series || item.title)].reduce((n,c) => n + c.charCodeAt(0), 0) % 6;
  return <div className={`poster poster-${hash} ${small ? 'poster-small' : ''}`}>
    {item.cover && !failed ? <img src={`art://${item.id}/cover?v=${encodeURIComponent(item.cover)}`} alt="" loading="lazy" onError={() => setFailed(true)}/> : <div className="poster-art"><span className="poster-edition">THE PERSONAL COLLECTION</span><div className="poster-orbit"/><span className="poster-type">{item.series || item.title}</span><span className="poster-genre">{item.genre} / {item.series ? 'SERIES' : 'FILM'}</span></div>}
    <div className="poster-glare"/>
    {item.watched && <span className="watched-badge" title="Watched"><Check size={13}/></span>}
    {!small && item.position > 0 && !item.watched && item.duration > 0 && <div className="poster-progress"><i style={{ width: `${Math.min(100,item.position / item.duration * 100)}%` }}/></div>}
  </div>;
}
function Card({ item, onPlay, onQueue, onEdit, onSeries }: { item: Media; onPlay: (i: Media) => void; onQueue: (i: Media) => void; onEdit: (i: Media) => void; onSeries?: (name: string) => void }) {
  const move = (e: React.PointerEvent<HTMLButtonElement>) => { const r = e.currentTarget.getBoundingClientRect(); const x = (e.clientX-r.left)/r.width; const y = (e.clientY-r.top)/r.height; e.currentTarget.style.setProperty('--rx', `${(0.5-y)*7}deg`); e.currentTarget.style.setProperty('--ry', `${(x-0.5)*9}deg`); e.currentTarget.style.setProperty('--gx', `${x*100}%`); e.currentTarget.style.setProperty('--gy', `${y*100}%`); };
  return <article className={`movie-card ${item.missing ? 'missing' : ''}`}>
    <button className="poster-button" disabled={item.missing} onPointerMove={move} onPointerLeave={e => { e.currentTarget.style.setProperty('--rx','0deg'); e.currentTarget.style.setProperty('--ry','0deg'); }} onClick={() => item.series && onSeries ? onSeries(item.series) : onPlay(item)} aria-label={`${item.series && onSeries ? 'Browse' : 'Play'} ${item.series && onSeries ? item.series : item.title}`}>
      <Poster item={item}/><span className="poster-play"><Play size={23} fill="currentColor"/></span>
    </button>
    <div className="card-heading"><h3 title={item.title}>{item.series && onSeries ? item.series : item.title}</h3><button className="card-menu" onClick={() => onEdit(item)} title={`Edit ${item.title}`} aria-label={`Edit ${item.title}`}><MoreHorizontal size={18}/></button></div>
    <div className="card-meta"><span>{item.missing ? 'File unavailable' : item.series ? 'Series' : item.duration ? `${Math.round(item.duration/60)} min` : item.genre}</span><button onClick={() => onQueue(item)} disabled={item.missing} title="Add to queue" aria-label={`Queue ${item.title}`}><Plus size={14}/></button></div>
  </article>;
}
function App() {
  const [data, setData] = useState<Snapshot>(initial); const [view,setView] = useState('Home'); const [query,setQuery] = useState(''); const [filter,setFilter] = useState('all');
  const [current,setCurrent] = useState<Media | null>(null); const [player,setPlayer] = useState(initialPlayer); const [fullscreen,setFullscreen] = useState(false);
  const [modal,setModal] = useState<'import' | 'settings' | Media | null>(null); const [toast,setToast] = useState(''); const [busy,setBusy] = useState('');
  const [clock,setClock] = useState(new Date()); const [countdown,setCountdown] = useState<number | null>(null); const [tracksOpen,setTracksOpen] = useState(false); const [idle,setIdle] = useState(false);
  const viewport = useRef<HTMLDivElement>(null); const opening = useRef(false); const preferenceRevision=useRef(0); const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null); const idleTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const notify = useCallback((message: string) => { setToast(message.replace(/^Error invoking remote method 'matinee': Error: /,'')); if (toastTimer.current) clearTimeout(toastTimer.current); toastTimer.current = setTimeout(() => setToast(''),6500); }, []);
  const guard = useCallback(async <T,>(work: () => Promise<T>): Promise<T | undefined> => { try { return await work(); } catch (e) { notify(e instanceof Error ? e.message : String(e)); } }, [notify]);
  const requireDesktop = () => { if (!api) { notify('Open the Matinee desktop app to choose local files.'); return false; } return true; };
  useEffect(() => { if (api) guard(async () => setData(await api.snapshot())); const timer = setInterval(() => setClock(new Date()),30000); const wake = () => setClock(new Date()); window.addEventListener('focus',wake); return () => { clearInterval(timer); window.removeEventListener('focus',wake); }; }, [guard]);
  const prefs = data.settings;
  useEffect(() => { document.documentElement.style.setProperty('--text-scale', String(prefs.textScale / 100)); }, [prefs.textScale]);
  const hour = clock.getHours(); const night = prefs.cinemaStart === prefs.cinemaEnd || (prefs.cinemaStart > prefs.cinemaEnd ? hour >= prefs.cinemaStart || hour < prefs.cinemaEnd : hour >= prefs.cinemaStart && hour < prefs.cinemaEnd);
  const dark = prefs.theme === 'cinema' || (prefs.theme === 'auto' && night);
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'cinema' : 'warm'; }, [dark]);
  const preferences = (patch: Partial<Settings>) => {
    const revision=++preferenceRevision.current;
    setData(d=>({...d,settings:{...d.settings,...patch}}));
    return guard(async()=>{if(!api)return;try{const settings=await api.settings(patch);if(revision===preferenceRevision.current)setData(d=>({...d,settings}));}catch(e){setData(await api.snapshot());throw e;}});
  };
  const queueItems = data.queue.map(id => data.items.find(i => i.id === id)).filter((i): i is Media => !!i && !i.missing);
  const recs = useMemo(() => suggested(data.items,current,prefs.shuffle),[data.items,current,prefs.shuffle]);
  const genres = [...new Set(data.items.map(i => i.genre))].sort();
  const updateQueue = async (ids: string[]) => { if (api) { const queue = await api.queue(ids); setData(d => ({ ...d, queue })); } };
  const addQueue = (item: Media, next = false) => guard(async () => { const rest = data.queue.filter(id => id !== item.id); await updateQueue(next ? [item.id,...rest] : [...rest,item.id]); notify(`${item.title} ${next ? 'plays next' : 'added to queue'}.`); });
  const play = async (item: Media) => {
    if (!requireDesktop()) return;
    if (opening.current) return;
    opening.current = true;
    setCountdown(null); setCurrent(item); setPlayer({ ...initialPlayer, loading: true }); setTracksOpen(false);
    try { await api!.play(item.id); await updateQueue(data.queue.filter(id => id !== item.id)); }
    catch (e) { setCurrent(null); notify(String(e)); }
    finally { opening.current = false; }
  };
  const control = (name: string,value?: number | string) => guard(async () => { await api?.control(name,value); if (name === 'volume' || name === 'speed') await preferences({ [name]: value }); });
  const leavePlayer = () => guard(async () => { setCountdown(null); setCurrent(null); setFullscreen(false); await api?.fullscreen(false); if (api) setData(await api.stop()); });
  const next = async () => {
    setCountdown(null); if (!current) return;
    if (prefs.repeat === 'one') { await control('seek',0); if (player.paused) await control('pause'); return; }
    let candidate = queueItems[0];
    if (prefs.repeat === 'queue') {
      candidate = candidate ?? current;
      const cycle = [...data.queue.filter(id => id !== candidate.id && id !== current.id), ...(candidate.id !== current.id ? [current.id] : [])];
      if (api) { setCurrent(candidate); await api.play(candidate.id); await updateQueue(cycle); } return;
    }
    candidate = candidate ?? recs[0];
    if (candidate) await play(candidate); else notify('You’ve reached the end. Time for the credits.');
  };
  useEffect(() => {
    if (!api) return;
    const offs = [api.on('library',setData), api.on('player',setPlayer), api.on('failure',(e: string) => { setCountdown(null); setPlayer(p => ({ ...p, loading: false })); notify(e); }), api.on('fullscreen',setFullscreen), api.on('ended',() => { if (prefs.autoplay) setCountdown(8); })];
    return () => offs.forEach(off => off());
  }, [prefs.autoplay,notify]);
  useEffect(() => { if (countdown == null) return; if (countdown === 0) { void guard(next); return; } const timer = setTimeout(() => setCountdown(c => c == null ? null : c-1),1000); return () => clearTimeout(timer); }, [countdown]);
  useEffect(() => { if (!prefs.autoplay) setCountdown(null); }, [prefs.autoplay]);
  useEffect(() => {
    if (!current || !api || !viewport.current) { void api?.viewport(null); return; }
    const element = viewport.current;
    const update = () => { const r = element.getBoundingClientRect(); void api.viewport({ x:r.x,y:r.y,width:r.width,height:r.height }); };
    const observer = new ResizeObserver(update); observer.observe(element); window.addEventListener('resize',update); update();
    return () => { observer.disconnect(); window.removeEventListener('resize',update); void api.viewport(null); };
  }, [current?.id,fullscreen]);
  useEffect(() => { void api?.obscure(!!modal); }, [modal]);
  useEffect(() => {
    const keyboard = (e: KeyboardEvent) => {
      if (e.key === 'Escape') { if (modal) setModal(null); else if (fullscreen) void api?.fullscreen(false); return; }
      if (e.target instanceof HTMLElement && (e.target.matches('input,textarea,select,button') || e.target.isContentEditable)) return;
      if (!current || modal) return;
      if ([' ','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','f','m'].includes(e.key)) e.preventDefault();
      if (e.key === ' ') void control('pause');
      if (e.key === 'ArrowLeft') void control('seek',Math.max(0,player.position-10));
      if (e.key === 'ArrowRight') void control('seek',Math.min(player.duration,player.position+10));
      if (e.key === 'ArrowUp') void control('volume',Math.min(100,player.volume+5));
      if (e.key === 'ArrowDown') void control('volume',Math.max(0,player.volume-5));
      if (e.key === 'm') void control('mute');
      if (e.key === 'f') void api?.fullscreen(!fullscreen);
    }; window.addEventListener('keydown',keyboard); return () => window.removeEventListener('keydown',keyboard);
  });
  const chooseRoot = () => guard(async () => { if (!requireDesktop()) return; setBusy('Opening library…'); try { setData(await api!.chooseRoot()); setCurrent(null); } finally { setBusy(''); } });
  const scan = () => guard(async () => { if (!requireDesktop()) return; setBusy('Refreshing library…'); try { setData(await api!.scan()); notify('Your library is up to date.'); } finally { setBusy(''); } });
  const filtered = data.items.filter(i => (!query || `${i.title} ${i.series} ${i.genre}`.toLowerCase().includes(query.toLowerCase())) && (filter === 'all' || (filter === 'unwatched' ? !i.watched : i.watched)));
  const cards = (items: Media[], group = true) => <div className="movie-grid">{(group ? seriesCards(items) : items).map(item => <Card key={item.id} item={item} onPlay={play} onQueue={addQueue} onEdit={setModal} onSeries={group ? name => setView(`series:${name}`) : undefined}/>)}</div>;
  const shelf = (title: string, items: Media[], subtitle?: string) => items.length > 0 && <section className="shelf"><div className="section-heading"><div><h2>{title}<span>{seriesCards(items).length}</span></h2>{subtitle && <p>{subtitle}</p>}</div><span className="shelf-line"/></div>{cards(items)}</section>;
  const moveQueue = (index: number,delta: number) => guard(async () => { const ids = [...data.queue]; const target = index+delta; if (target < 0 || target >= ids.length) return; [ids[index],ids[target]]=[ids[target],ids[index]]; await updateQueue(ids); });
  const activity = () => { setIdle(false); if (idleTimer.current) clearTimeout(idleTimer.current); idleTimer.current = setTimeout(() => setIdle(true),2800); };
  return <div className={`app ${current ? 'watching' : ''} ${fullscreen ? 'is-fullscreen' : ''}`} onPointerMove={activity}>
    <div className="titlebar"><span className="titlebar-label">MATINEE <span> / </span> A LITTLE TIME FOR A GOOD FILM</span><div className="window-actions"><IconButton label="Minimize window" onClick={() => api?.window('minimize')}><Minus size={14}/></IconButton><IconButton label="Maximize window" onClick={() => api?.window('maximize')}><Square size={11}/></IconButton><IconButton label="Close window" onClick={() => api?.window('close')}><X size={15}/></IconButton></div></div>
    {!current && <aside className="sidebar"><a className="brand" href="#" onClick={e => { e.preventDefault(); setView('Home'); }}><span className="brand-icon"><Clapperboard size={24}/></span><span>Matinee<span className="brand-dot">.</span><small>YOUR OWN LITTLE CINEMA</small></span></a>
      <div className="sidebar-label">YOUR SPACE</div><nav>{[{ name:'Home',icon:House },{ name:'Movies',icon:Film },{ name:'Series',icon:Tv },{ name:'Queue',icon:ListOrdered }].map(({name,icon:Icon}) => <button key={name} className={view === name ? 'selected' : ''} onClick={() => { setView(name); setQuery(''); }}><Icon size={18}/><span>{name}</span>{name === 'Queue' && <span className="nav-count">{queueItems.length}</span>}</button>)}</nav>
      <div className="sidebar-label genres-label">THE SHELVES<span>{genres.length.toString().padStart(2,'0')}</span></div><nav className="genre-nav">{genres.length ? genres.map((genre,index) => <button key={genre} className={view === `genre:${genre}` ? 'selected' : ''} onClick={() => setView(`genre:${genre}`)}><i className={`genre-dot dot-${index%5}`}/><span>{genre}</span><span className="genre-count">{seriesCards(data.items.filter(i => i.genre === genre)).length}</span></button>) : <p className="shelves-empty">Your genres will find<br/>a home here.</p>}</nav>
      <div className="sidebar-bottom"><div className="local-note"><span className="status-dot"/>Entirely yours. Entirely local.</div><button className="library-location" onClick={chooseRoot} title={data.root || 'Choose a library folder'}><FolderOpen size={17}/><span>{data.root ? data.root.split(/[\\/]/).filter(Boolean).pop() : 'Choose library folder'}<small>{data.root ? 'Your movie library' : 'Give your films a home'}</small></span><ChevronDown size={13}/></button><button className="settings-nav" onClick={() => setModal('settings')}><Settings2 size={17}/>Settings & preferences</button></div>
    </aside>}
    <main className={current ? 'watch-main' : 'main'}>
      {!current ? <><header className="topbar"><div className="breadcrumb">Your collection <span>/</span> <strong>{view.startsWith('genre:') || view.startsWith('series:') ? view.split(':').slice(1).join(':') : view}</strong></div><div className="topbar-actions"><label className="search"><Search size={16}/><input placeholder="Find your next watch" aria-label="Search library" value={query} onChange={e => setQuery(e.target.value)}/><kbd>⌕</kbd></label><IconButton label={`Switch to ${dark ? 'warm' : 'cinema'} theme`} onClick={() => preferences({ theme:dark ? 'warm' : 'cinema' })}>{dark ? <Moon size={18}/> : <Sun size={19}/>}</IconButton><button className="button primary add-button" onClick={() => data.root ? setModal('import') : chooseRoot()}><Plus size={16}/>Add a movie</button></div></header>
        <div className="library-content">
          {view === 'Home' && !query && <section className="hero"><div className="hero-copy"><span className="eyebrow"><span className="status-dot"/>{dark ? 'THE LIGHTS ARE LOW. SETTLE IN.' : 'SLOW DOWN. PRESS PLAY.'}</span><h1>Good films.<br/><em>Your own time.</em></h1><p>{data.items.length ? 'An old favourite. Something unexpected.\nYour next great watch is already here.' : 'A home for the films you love.\nNo feeds, no noise. Just you and the story.'}</p><div className="hero-actions"><button className="button primary" onClick={() => { const resume = data.items.find(i => i.position > 0 && !i.watched && !i.missing); if (resume) void play(resume); else if (!data.root) void chooseRoot(); else setModal('import'); }}>{data.items.some(i => i.position > 0 && !i.watched) ? <Play size={15} fill="currentColor"/> : <FolderOpen size={16}/>} {data.items.some(i => i.position > 0 && !i.watched) ? 'Pick up where you left off' : data.root ? 'Add your first feature' : 'Choose your movie folder'}<ArrowRight size={16}/></button><span className="hero-footnote">{data.items.length ? `${data.items.length} stories, one little cinema` : 'Your collection starts here'}</span></div></div><div className="hero-art" aria-hidden="true"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-ticket"><span>MATINEE PICTURE HOUSE</span><div className="ticket-symbol"><Sparkles size={30}/></div><strong>ADMIT<br/>YOURSELF.</strong><div className="ticket-rule"/><small>ANY FILM · ANY TIME</small><div className="ticket-bottom"><span>SEAT<br/><b>01</b></span><span>SCREEN<br/><b>YOURS</b></span><div className="barcode"/></div></div><span className="art-caption">THE BEST SEAT IS THE ONE AT HOME.</span></div><span className="hero-index">EST. YOUR TIME</span></section>}
          <div className="collection-toolbar"><div><span className="eyebrow">{view === 'Queue' ? 'ONE GOOD FILM AFTER ANOTHER' : view.startsWith('series:') ? 'IN THE RIGHT ORDER' : 'CURATED BY YOU'}</span><h2>{query ? `Results for “${query}”` : view === 'Home' ? 'On your shelves' : view.replace(/^(genre|series):/,'')}</h2></div><div className="toolbar-options"><label><SlidersHorizontal size={14}/><select aria-label="Watched filter" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All titles</option><option value="unwatched">Unwatched</option><option value="watched">Watched</option></select></label><IconButton label="Refresh library" disabled={!data.root || !!busy} onClick={scan}><RefreshCw size={16} className={busy ? 'spin' : ''}/></IconButton></div></div>
          {view === 'Queue' ? <div className="queue-panel">{queueItems.length ? <><div className="queue-summary"><p>{queueItems.length} titles waiting in the wings.</p><button className="button secondary" onClick={() => guard(() => updateQueue([]))}>Clear queue</button></div>{queueItems.map((item,index) => <div className="queue-row" key={item.id} draggable onDragStart={e => e.dataTransfer.setData('text/plain',item.id)} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const from = data.queue.indexOf(e.dataTransfer.getData('text/plain')); if (from >= 0) void moveQueue(from,index-from); }}><GripVertical size={16}/><span className="queue-number">{String(index+1).padStart(2,'0')}</span><Poster item={item} small/><button className="queue-title" onClick={() => play(item)}><strong>{item.title}</strong><small>{item.series || item.genre}</small></button><IconButton label="Move earlier" disabled={index===0} onClick={() => moveQueue(index,-1)}><ArrowUp size={15}/></IconButton><IconButton label="Move later" disabled={index===queueItems.length-1} onClick={() => moveQueue(index,1)}><ArrowDown size={15}/></IconButton><IconButton label="Remove from queue" onClick={() => guard(() => updateQueue(data.queue.filter(id => id !== item.id)))}><X size={16}/></IconButton></div>)}</> : <Empty title="A little room for what’s next." body="Add titles with the + on each card, then arrange your perfect double feature." icon={<ListOrdered size={28}/>}/>}</div>
            : !data.items.length ? <Empty title={data.root ? 'The screen is yours.' : 'Every collection starts with a first film.'} body={data.root ? 'Add a local movie and its cover art, or put films in your folder and refresh.' : 'Choose a folder of movies you already own. We’ll arrange the shelves; you bring the popcorn.'} icon={<Film size={30}/>} action={<button className="button secondary" onClick={() => data.root ? setModal('import') : chooseRoot()}><Plus size={15}/>{data.root ? 'Add a movie' : 'Set up your library'}</button>}/>
            : query ? (filtered.length ? cards(filtered) : <Empty title="No titles found." body="Try a different title, series, or genre." icon={<Search size={26}/>}/>)
            : view === 'Home' ? <>{shelf('Continue watching',filtered.filter(i => i.position > 0 && !i.watched && !i.missing).sort((a,b) => (b.lastWatched??0)-(a.lastWatched??0)),'Right where you left the story.')}{shelf('Recently added',[...filtered].sort((a,b)=>b.addedAt-a.addedAt).slice(0,8))}{genres.map(genre => <React.Fragment key={genre}>{shelf(genre,filtered.filter(i => i.genre === genre))}</React.Fragment>)}</>
            : view === 'Movies' ? cards(filtered.filter(i => !i.series))
            : view === 'Series' ? cards(filtered.filter(i => i.series))
            : view.startsWith('series:') ? cards(filtered.filter(i => i.series === view.slice(7)).sort(episodeSort),false)
            : cards(filtered.filter(i => i.genre === view.slice(6)))}
          <footer className="library-footer"><span><Clapperboard size={13}/> A quieter kind of movie night.</span><span>{dark ? <Moon size={12}/> : <Sun size={13}/>} {dark ? 'Cinema' : 'Warm'} mode {prefs.theme==='auto' && '· following your day'}</span></footer>
        </div></> : <>
          {!fullscreen && <header className="watch-header"><button className="text-button" onClick={leavePlayer}><ArrowLeft size={17}/>Back to your collection</button><span className="eyebrow">NOW SHOWING AT MATINEE</span><button className="text-button" onClick={() => preferences({theme:dark?'warm':'cinema'})}>{dark?<Moon size={16}/>:<Sun size={16}/>}</button></header>}
          <div className="watch-layout"><section className="watch-primary"><div className="screen" ref={viewport} onDoubleClick={() => api?.fullscreen(!fullscreen)}><Clapperboard size={42}/><span>{player.loading ? 'Setting the scene…' : 'Your local cinema'}</span></div>
            <div className={`player-controls ${fullscreen && idle && !player.paused && !tracksOpen && countdown == null ? 'controls-idle' : ''}`} onFocus={() => setIdle(false)}><input className="seek" aria-label="Playback position" type="range" min="0" max={player.duration || 1} step="0.1" value={Math.min(player.position,player.duration || 1)} onChange={e => control('seek',Number(e.target.value))}/><div className="controls-row"><IconButton label={player.paused?'Play':'Pause'} onClick={() => control('pause')}>{player.paused?<Play size={21} fill="currentColor"/>:<Pause size={21} fill="currentColor"/>}</IconButton><IconButton label="Play next" onClick={() => guard(next)}><SkipForward size={19}/></IconButton><IconButton label={player.muted?'Unmute':'Mute'} onClick={() => control('mute')}>{player.muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</IconButton><input className="volume" type="range" aria-label="Volume" min="0" max="100" value={player.volume} onChange={e => control('volume',Number(e.target.value))}/><span className="play-time">{time(player.position)}<i>/</i>{time(player.duration)}</span><div className="controls-spacer"/><select className="speed" aria-label="Playback speed" value={player.speed} onChange={e => control('speed',Number(e.target.value))}>{[.25,.5,.75,1,1.25,1.5,1.75,2,2.5,3].map(n=><option key={n} value={n}>{n}×</option>)}</select><IconButton label="Subtitles and audio" active={tracksOpen} onClick={() => setTracksOpen(!tracksOpen)}><Subtitles size={20}/></IconButton><IconButton label={fullscreen?'Exit fullscreen':'Fullscreen'} onClick={() => api?.fullscreen(!fullscreen)}>{fullscreen?<Minimize size={19}/>:<Maximize size={19}/>}</IconButton></div>
              {tracksOpen && <div className="track-settings"><label>Subtitles<select value={player.tracks.find(t=>t.type==='sub'&&t.selected)?.id ?? 'no'} onChange={e => control('subtitle',e.target.value==='no'?'no':Number(e.target.value))}><option value="no">Off</option>{player.tracks.filter(t=>t.type==='sub').map(t=><option key={t.id} value={t.id}>{t.title || t.lang || `Track ${t.id}`}</option>)}</select></label><button className="button secondary" onClick={() => guard(async () => { await api?.pick('subtitle'); })}>Load subtitle file</button><label>Audio<select value={player.tracks.find(t=>t.type==='audio'&&t.selected)?.id ?? ''} onChange={e=>control('audio',Number(e.target.value))}>{player.tracks.filter(t=>t.type==='audio').map(t=><option key={t.id} value={t.id}>{t.title||t.lang||`Track ${t.id}`}</option>)}</select></label><label>Subtitle offset (seconds)<input type="number" step="0.1" value={player.subtitleDelay??0} onChange={e=>control('subtitleDelay',Number(e.target.value))}/></label></div>}
              {countdown != null && <div className="up-next-countdown"><span>Next title in {countdown}s</span><button className="text-button" onClick={() => setCountdown(null)}>Stay here</button><button className="button primary" onClick={() => guard(next)}>Play now</button></div>}
            </div>
            {!fullscreen && <div className="now-playing"><div><span className="eyebrow">{current.series ? `${current.series} · S${current.season ?? 0} E${current.episode ?? 0}` : current.genre}</span><h1>{current.title}</h1><p><span className="status-dot"/>Playing from your library <span>·</span> {current.file.split(/[\\/]/).pop()}</p></div><IconButton label="Mark watched" onClick={() => guard(async()=>{if(api)setData(await api.markWatched(current.id,true));notify('Marked as watched.');})}><CheckCheck size={21}/></IconButton></div>}
          </section>{!fullscreen && <aside className="up-next"><div className="up-next-title"><h2>Up next</h2><label className="toggle-label">Autoplay<input type="checkbox" checked={prefs.autoplay} onChange={e=>preferences({autoplay:e.target.checked})}/><span className="toggle"/></label></div><div className="playback-options"><button className={prefs.shuffle?'active':''} onClick={()=>preferences({shuffle:!prefs.shuffle})}><Shuffle size={14}/>Shuffle suggestions</button><button className={prefs.repeat!=='off'?'active':''} onClick={()=>preferences({repeat:prefs.repeat==='off'?'one':prefs.repeat==='one'?'queue':'off'})}><Repeat size={14}/>{prefs.repeat==='off'?'Repeat off':prefs.repeat==='one'?'Repeat one':'Repeat queue'}</button></div><p className="suggestion-label">{queueItems.length ? 'YOUR QUEUE, THEN YOUR COLLECTION' : current.series ? 'THE NEXT CHAPTER' : 'MORE FROM YOUR COLLECTION'}</p>{[...queueItems,...recs.filter(i=>!data.queue.includes(i.id))].slice(0,12).map((item,index)=><div className="suggestion" key={item.id}><button className="suggestion-cover" onClick={()=>play(item)}><Poster item={item} small/></button><button className="suggestion-title" onClick={()=>play(item)}><small>{index===0?'NEXT UP':item.series?'SERIES':item.genre.toUpperCase()}</small><strong>{item.title}</strong><span>{item.series?`S${item.season??0} · E${item.episode??0}`:item.genre}</span></button><IconButton label="Play this next" onClick={()=>addQueue(item,true)}><Plus size={15}/></IconButton></div>)}{!queueItems.length&&!recs.length&&<p className="shelves-empty">The credits can wait.<br/>Add more films to find your next watch.</p>}</aside>}</div>
        </>}
    </main>
    {busy && <div className="busy-pill"><RefreshCw size={14} className="spin"/>{busy}</div>}
    {toast && <div className="toast" role="status"><span>{toast}</span><button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
    {modal && <Modal title={modal==='settings'?'Make yourself comfortable.':modal==='import'?'A new addition to the shelves.':'A little fine-tuning.'} onClose={()=>setModal(null)}>
      {modal==='settings'?<SettingsPanel data={data} change={preferences} chooseRoot={chooseRoot}/>:<MovieForm item={typeof modal==='object'?modal:undefined} genres={genres} notify={notify} onSaved={snapshot=>{setData(snapshot);setModal(null);notify(typeof modal==='object'?'Changes saved.':'Your movie is on the shelf.');}}/>}
    </Modal>}
  </div>;
}
function Empty({title,body,icon,action}:{title:string;body:string;icon:React.ReactNode;action?:React.ReactNode}){return <div className="empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{body}</p>{action}<span className="empty-caption">LOCAL FILES. LIMITLESS REWATCHES.</span></div>;}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) {
  const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement;const el=ref.current;el?.querySelector<HTMLElement>('button,input')?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const nodes=el?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};el?.addEventListener('keydown',trap);return()=>{el?.removeEventListener('keydown',trap);previous?.focus();};},[]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" ref={ref}><header><span className="eyebrow">MATINEE / YOUR COLLECTION</span><IconButton label="Close dialog" onClick={onClose}><X size={19}/></IconButton></header><h2 id="modal-title">{title}</h2>{children}</div></div>;
}
function SettingsPanel({data,change,chooseRoot}:{data:Snapshot;change:(p:Partial<Settings>)=>unknown;chooseRoot:()=>unknown}) {return <div className="settings-panel"><p className="muted">Small details for a better movie night. Everything stays on this PC.</p><section className="text-size-setting" aria-labelledby="text-size-label">
      <div className="text-size-heading"><label id="text-size-label" htmlFor="text-size">Text size</label><output htmlFor="text-size">{data.settings.textScale}%</output></div>
      <p className="muted">Make menus, movie titles, and controls comfortable to read. Changes apply immediately and stay saved on this PC.</p>
      <div className="text-size-controls">
        <IconButton label="Decrease text size" disabled={data.settings.textScale <= 100} onClick={() => change({textScale: data.settings.textScale - 5})}><Minus size={18}/></IconButton>
        <input id="text-size" type="range" min="100" max="200" step="5" value={data.settings.textScale} aria-valuetext={data.settings.textScale + '%'} onChange={e => change({textScale: Number(e.target.value)})}/>
        <IconButton label="Increase text size" disabled={data.settings.textScale >= 200} onClick={() => change({textScale: data.settings.textScale + 5})}><Plus size={18}/></IconButton>
      </div>
      <div className="text-size-presets">{[100,125,150,175,200].map(size => <button key={size} type="button" aria-pressed={data.settings.textScale === size} onClick={() => change({textScale:size})}>{size}%</button>)}</div>
      <div className="text-size-preview"><strong>Your next great watch.</strong><span>A comfortable size for every story.</span></div>
      <button className="text-button" type="button" onClick={() => change({textScale:125})}>Reset to recommended (125%)</button>
    </section><label className="field-label">THE ATMOSPHERE</label><div className="theme-options">{[{value:'auto',label:'Follow the day',icon:Monitor},{value:'warm',label:'Warm',icon:Sun},{value:'cinema',label:'Cinema',icon:Moon}].map(({value,label,icon:Icon})=><button className={data.settings.theme===value?'selected':''} key={value} onClick={()=>change({theme:value as Settings['theme']})}><Icon size={21}/><span>{label}</span>{data.settings.theme===value&&<Check size={13}/>}</button>)}</div><div className="form-row"><label>Cinema begins<select value={data.settings.cinemaStart} onChange={e=>change({cinemaStart:Number(e.target.value)})}>{Array.from({length:24},(_,h)=><option value={h} key={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label>Warm returns<select value={data.settings.cinemaEnd} onChange={e=>change({cinemaEnd:Number(e.target.value)})}>{Array.from({length:24},(_,h)=><option value={h} key={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label></div><div className="settings-divider"/><label className="field-label">YOUR LIBRARY</label><button className="folder-setting" onClick={()=>chooseRoot()}><FolderOpen size={21}/><span>{data.root||'Choose a folder'}<small>Click to choose a different local library</small></span><ArrowRight size={16}/></button><div className="settings-note"><Subtitles size={20}/><div><strong>Captions, without the cloud.</strong><p>Embedded captions and local subtitle files are supported. Offline automatic caption generation is planned for a later release.</p></div></div><div className="settings-note"><span className="status-dot"/><div><strong>{data.playerReady?'Native player ready':'Playback engine not installed'}</strong><p>{data.playerReady?'mpv handles your local video, audio and subtitle tracks.':'Run npm run setup:player during development to install mpv.'}</p></div></div><p className="version">MATINEE {appVersion} · MADE FOR SLOW EVENINGS</p></div>;}
function MovieForm({item,genres,onSaved,notify}:{item?:Media;genres:string[];onSaved:(d:Snapshot)=>void;notify:(m:string)=>void}) {
  const [title,setTitle]=useState(item?.title??'');const [genre,setGenre]=useState(item?.genre??genres[0]??'Drama');const [series,setSeries]=useState(item?.series??'');
  const [season,setSeason]=useState(String(item?.season??1));const [episode,setEpisode]=useState(String(item?.episode??1));const [order,setOrder]=useState(item?.order!=null?String(item.order):'');
  const [filename,setFilename]=useState(item?.file.split(/[\\/]/).pop()?.replace(/\.[^.]+$/,'')??'');
  const [foldername,setFoldername]=useState(item?.file.split(/[\\/]/).slice(-2,-1)[0]??'');
  const [video,setVideo]=useState<SelectedFile|null>(null);const [cover,setCover]=useState<SelectedFile|null>(null);const [working,setWorking]=useState(false);const [progress,setProgress]=useState(0);const [error,setError]=useState('');
  useEffect(()=>api?.on('progress',p=>setProgress(p.percent)),[]);
  const select=async(kind:'video'|'cover')=>{try{const file=await api?.pick(kind);if(file){if(kind==='video'){setVideo(file);if(!title)setTitle(file.name.replace(/\.[^.]+$/,''));}else setCover(file);}}catch(e){setError(String(e));}};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!api)return;setWorking(true);setError('');try{const payload={title,genre,series,season:series?Number(season):null,episode:series?Number(episode):null,order:order!==''?Number(order):null};const result=item?await api.edit(item.id,{...payload,filename,foldername,coverToken:cover?.token}):await api.importMovie({...payload,videoToken:video?.token,coverToken:cover?.token});onSaved(result);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setWorking(false);}};
  return <form className="movie-form" onSubmit={submit}><p className="muted">{item?'Edit the display title and filename separately. Your place in the story stays saved.':'Pick a local video and its artwork. We copy them into your library and keep the originals.'}</p><fieldset disabled={working}>
    {!item&&<div className="file-pickers"><button type="button" onClick={()=>select('video')}><Upload size={23}/><strong>{video?.name??'Choose a movie'}</strong><small>MP4, MKV, MOV, AVI & more</small></button><button type="button" onClick={()=>select('cover')}><ImagePlus size={23}/><strong>{cover?.name??'Choose cover art'}</strong><small>JPG, PNG, WebP or BMP · optional</small></button></div>}
    <label>Display title<input required maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="The name on the marquee"/></label><div className="form-row"><label>Genre<input required list="genres" value={genre} onChange={e=>setGenre(e.target.value)}/><datalist id="genres">{genres.map(g=><option key={g}>{g}</option>)}</datalist></label><label>Series <span className="optional">optional</span><input value={series} onChange={e=>setSeries(e.target.value)} placeholder="Leave blank for a movie"/></label></div>
    {series&&<div className="form-row"><label>Season<input type="number" min="0" required value={season} onChange={e=>setSeason(e.target.value)}/></label><label>Episode<input type="number" min="0" required value={episode} onChange={e=>setEpisode(e.target.value)}/></label><label>Custom order<input type="number" min="0" value={order} onChange={e=>setOrder(e.target.value)} placeholder="Auto"/></label></div>}
    {item&&<label>Video filename <span className="optional">extension stays the same</span><input required value={filename} onChange={e=>setFilename(e.target.value)}/></label>}
    {item&&item.file.split(/[\\/]/).length>=3&&<label>Containing folder <span className="optional">includes any sibling files</span><input required value={foldername} onChange={e=>setFoldername(e.target.value)}/></label>}
    {item&&<button className="button secondary" type="button" onClick={()=>select('cover')}><ImagePlus size={16}/>{cover?.name??'Replace cover art'}</button>}
    </fieldset>{error&&<p className="form-error" role="alert">{error.replace(/^Error invoking remote method 'matinee': Error: /,'')}</p>}{working&&<div className="import-progress"><progress value={progress} max="100"/><span>{item?'Saving changes…':`Copying to your library… ${progress}%`}</span>{!item&&<button type="button" className="text-button" onClick={()=>api?.cancelImport()}>Cancel copy</button>}</div>}
    <div className="form-footer">{item&&<button type="button" className="text-button" onClick={async()=>{try{if(api)onSaved(await api.markWatched(item.id,!item.watched));}catch(e){notify(String(e));}}}><CheckCheck size={16}/>{item.watched?'Mark unwatched':'Mark watched'}</button>}<button className="button primary" type="submit" disabled={working||(!item&&!video)}>{item?<Check size={16}/>:<Plus size={16}/>} {item?'Save changes':'Add to your collection'}</button></div>
  </form>;
}
createRoot(document.getElementById('root')!).render(<App/>);
