import {useEffect,useState} from 'react';
import {Check,CheckCheck,FolderOpen,ImagePlus,Plus,Trash2,Upload} from 'lucide-react';
import {api,parts} from './state';
import {IconButton} from './ui';
import type {Media,SelectedFile,Snapshot} from './types';
export function MovieForm({item,data,onSaved,onHide}:{item?:Media;data:Snapshot;onSaved:()=>void;onHide:(item:Media)=>void}){
 const[title,setTitle]=useState(item?.title??''),[genre,setGenre]=useState(item?.genre??''),[series,setSeries]=useState(item?.series??'');
 const[season,setSeason]=useState(String(item?.season??1)),[episode,setEpisode]=useState(String(item?.episode??1)),[order,setOrder]=useState(item?.order!=null?String(item.order):'');
 const[filename,setFilename]=useState(parts(item?.file??'').pop()?.replace(/\.[^.]+$/,'')??''),[foldername,setFoldername]=useState(parts(item?.file??'').slice(-2,-1)[0]??'');
 const[folder,setFolder]=useState(data.browser.path),[video,setVideo]=useState<SelectedFile|null>(null),[cover,setCover]=useState<SelectedFile|null>(null);
 const[working,setWorking]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('');
 useEffect(()=>api?.on('progress',p=>setProgress(p.percent)),[]);
 const attempt=async(work:()=>Promise<unknown>|undefined)=>{try{await work();}catch(e){setError((e instanceof Error?e.message:String(e)).replace(/^Error invoking remote method 'astra': Error: /,''));}};
 const select=async(kind:'video'|'cover')=>attempt(async()=>{const file=await api?.pick(kind);if(file){if(kind==='video'){setVideo(file);const stem=file.name.replace(/\.[^.]+$/,'');setFilename(stem);if(!title)setTitle(stem);}else setCover(file);}});
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!api)return;setWorking(true);setError('');try{const payload={title,genre:genre||'Unsorted',series,season:series?Number(season):null,episode:series?Number(episode):null,order:order!==''?Number(order):null};if(item)await api.edit(item.id,{...payload,filename,foldername,coverToken:cover?.token});else await api.importMovie({...payload,filename,folder,videoToken:video?.token,coverToken:cover?.token});onSaved();}catch(e){setError((e instanceof Error?e.message:String(e)).replace(/^Error invoking remote method 'astra': Error: /,''));}finally{setWorking(false);}};
 return <form className="movie-form" onSubmit={submit}><p className="muted">{item?'Edit the display title and filename separately. Your place in the story stays saved.':'Copy a video into the folder you choose. Your original files stay untouched.'}</p><fieldset disabled={working}>
  {!item&&<><button type="button" className="folder-setting import-destination" onClick={()=>attempt(async()=>{const selected=await api?.chooseDestination();if(selected!=null)setFolder(selected);})}><FolderOpen size={20}/><span>Destination: {folder||parts(data.root).pop()||'Library'}<small>Click to choose a folder inside your library</small></span></button><div className="file-pickers"><button type="button" onClick={()=>select('video')}><Upload size={23}/><strong>{video?.name??'Choose a video'}</strong><small>MP4, MKV, MOV, AVI, WMV & more</small></button><button type="button" onClick={()=>select('cover')}><ImagePlus size={23}/><strong>{cover?.name??'Choose cover art'}</strong><small>JPG, PNG, WebP or BMP · optional</small></button></div></>}
  <label>Display title<input required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} placeholder="The name on the marquee"/></label><div className="form-row"><label>Genre <input list="genres" value={genre} onChange={e=>setGenre(e.target.value)} placeholder="Optional"/><datalist id="genres">{[...new Set(data.items.map(i=>i.genre))].map(g=><option key={g}>{g}</option>)}</datalist></label><label>Series <input value={series} onChange={e=>setSeries(e.target.value)} placeholder="Optional"/></label></div>
  {series&&<div className="form-row"><label>Season<input type="number" min="0" required value={season} onChange={e=>setSeason(e.target.value)}/></label><label>Episode<input type="number" min="0" required value={episode} onChange={e=>setEpisode(e.target.value)}/></label><label>Custom order<input type="number" min="0" value={order} onChange={e=>setOrder(e.target.value)} placeholder="Auto"/></label></div>}
  <label>Video filename <span className="optional">extension stays the same</span><input required value={filename} onChange={e=>setFilename(e.target.value)}/></label>
  {item&&parts(item.file).length>=3&&<label>Containing folder <span className="optional">includes any sibling files</span><input required value={foldername} onChange={e=>setFoldername(e.target.value)}/></label>}
  {item&&<div className="cover-actions"><button className="button secondary" type="button" onClick={()=>select('cover')}><ImagePlus size={16}/>{cover?.name??'Replace cover art'}</button>{item.cover&&<IconButton label="Reset cover art" onClick={()=>attempt(async()=>{await api?.resetCover(item.id);setCover(null);})}><Trash2 size={18}/></IconButton>}</div>}
  </fieldset>{error&&<p className="form-error" role="alert">{error}</p>}{working&&<div className="import-progress"><progress value={progress} max="100"/><span>{item?'Saving changes…':`Copying to your library… ${progress}%`}</span>{!item&&<button type="button" className="text-button" onClick={()=>api?.cancelImport()}>Cancel copy</button>}</div>}
  <div className="form-footer">{item&&<><button type="button" className="text-button" disabled={working} onClick={()=>attempt(async()=>{await api?.markWatched(item.id,!item.watched);})}><CheckCheck size={16}/>{item.watched?'Mark unwatched':'Mark watched'}</button><IconButton label="Hide from Astra" disabled={working} onClick={()=>onHide(item)}><Trash2 size={19}/></IconButton></>}<button className="button primary" type="submit" disabled={working||(!item&&!video)}>{item?<Check size={16}/>:<Plus size={16}/>} {item?'Save changes':'Add to your collection'}</button></div>
 </form>;
}
