import {ArrowDown,ArrowUp,GripVertical,Play,Plus,Repeat,Shuffle,Trash2,X} from 'lucide-react';
import type {Media,Settings,Snapshot} from './types';
import {IconButton,Poster,Empty} from './ui';
import {api} from './state';
type Run=<T>(work:()=>Promise<T>|undefined)=>Promise<T|undefined>;
export function QueueView({data,run,compact=false}:{data:Snapshot;run:Run;compact?:boolean}){
 const items=data.queue.map(id=>data.items.find(i=>i.id===id)).filter((i):i is Media=>!!i&&!i.hidden&&!i.missing);
 const move=(index:number,target:number)=>{if(target<0||target>=data.queue.length)return;const ids=[...data.queue];const[id]=ids.splice(index,1);ids.splice(target,0,id);void run(()=>api?.queue('reorder',ids));};
 return <section className={`queue-section ${compact?'compact-queue':''}`} aria-label="Queue"><div className="queue-section-heading"><h2>Queue <span>{items.length}</span></h2><IconButton label="Play queue" disabled={!items.length} onClick={()=>run(()=>api?.playQueue())}><Play size={19}/></IconButton><IconButton label="Clear queue" disabled={!items.length} onClick={()=>run(()=>api?.queue('clear'))}><Trash2 size={18}/></IconButton></div>{items.map((item,index)=><div className="queue-row" key={item.id} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',item.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const from=data.queue.indexOf(e.dataTransfer.getData('text/plain'));if(from>=0)move(from,index);}}>{!compact&&<><GripVertical size={16}/><span className="queue-number">{String(index+1).padStart(2,'0')}</span></>}<Poster item={item} small/><button className="queue-title" onClick={()=>run(()=>api?.play(item.id))}><strong>{item.title}</strong><small>{item.series||item.genre}</small></button><IconButton label={`Play queued ${item.title}`} onClick={()=>run(()=>api?.play(item.id))}><Play size={16}/></IconButton>{!compact&&<><IconButton label={`Move ${item.title} earlier`} disabled={index===0} onClick={()=>move(index,index-1)}><ArrowUp size={15}/></IconButton><IconButton label={`Move ${item.title} later`} disabled={index===items.length-1} onClick={()=>move(index,index+1)}><ArrowDown size={15}/></IconButton></>}<IconButton label={`Remove ${item.title} from queue`} onClick={()=>run(()=>api?.queue('remove',item.id))}><X size={16}/></IconButton></div>)}{!items.length&&(compact?<p className="muted queue-empty">Add videos with +. Oldest additions play first when Shuffle is off.</p>:<Empty title="A little room for what’s next." body="Add videos with +, then press Play queue. You can also drag them into your preferred order." icon={<Play size={25}/>}/> )}</section>;
}
export function PlaybackOptions({settings,onChange}:{settings:Settings;onChange:(patch:Partial<Settings>)=>unknown}){return <div className="playback-options"><label className="toggle-label">Autoplay<input type="checkbox" checked={settings.autoplay} onChange={e=>onChange({autoplay:e.target.checked})}/><span className="toggle"/></label><button className={settings.shuffle?'active':''} aria-pressed={settings.shuffle} onClick={()=>onChange({shuffle:!settings.shuffle})}><Shuffle size={15}/>Shuffle {settings.shuffle?'on':'off'}</button><button className={settings.repeat!=='off'?'active':''} onClick={()=>onChange({repeat:settings.repeat==='off'?'one':settings.repeat==='one'?'all':'off'})}><Repeat size={15}/>Repeat {settings.repeat}</button></div>;}
export function UpNext({data,run}:{data:Snapshot;run:Run}){const items=data.upNext.map(id=>data.items.find(i=>i.id===id)).filter((i):i is Media=>!!i);return <section aria-label="Up next"><div className="up-next-title"><h2>Up next</h2><span className="sort-label">Name A–Z</span></div><p className="suggestion-label">IN THIS VIDEO’S FOLDER</p>{items.map(item=><div className="suggestion" key={item.id}><button className="suggestion-cover" aria-label={`Play ${item.title}`} onClick={()=>run(()=>api?.play(item.id))}><Poster item={item} small/></button><button className="suggestion-title" onClick={()=>run(()=>api?.play(item.id))}><strong>{item.title}</strong><span>{item.series||item.genre}</span></button><IconButton label={`Queue ${item.title}`} onClick={()=>run(()=>api?.queue('append',item.id))}><Plus size={18}/></IconButton></div>)}{!items.length&&<p className="muted">No other videos in this folder.</p>}</section>;}
