import {Check,FolderOpen,Minus,Monitor,Moon,Plus,Sun,Undo2} from 'lucide-react';
import {IconButton} from './ui';
import {api} from './state';
import type {Settings,Snapshot} from './types';
import {version} from '../package.json';
export function SettingsPanel({data,change,run}:{data:Snapshot;change:(patch:Partial<Settings>)=>unknown;run:<T>(work:()=>Promise<T>|undefined)=>Promise<T|undefined>}){
 const hidden=data.items.filter(i=>i.hidden);
 return <div className="settings-panel"><p className="muted">Small details for a better movie night. Everything stays on this PC.</p>
  <section className="text-size-setting" aria-labelledby="text-size-label"><div className="text-size-heading"><label id="text-size-label" htmlFor="text-size">Text size</label><output htmlFor="text-size">{data.settings.textScale}%</output></div><p className="muted">Make menus, video titles, and controls comfortable to read.</p><div className="text-size-controls"><IconButton label="Decrease text size" disabled={data.settings.textScale<=100} onClick={()=>change({textScale:data.settings.textScale-5})}><Minus size={18}/></IconButton><input id="text-size" type="range" min="100" max="200" step="5" value={data.settings.textScale} aria-valuetext={`${data.settings.textScale}%`} onChange={e=>change({textScale:Number(e.target.value)})}/><IconButton label="Increase text size" disabled={data.settings.textScale>=200} onClick={()=>change({textScale:data.settings.textScale+5})}><Plus size={18}/></IconButton></div><div className="text-size-presets">{[100,125,150,175,200].map(size=><button key={size} aria-pressed={data.settings.textScale===size} onClick={()=>change({textScale:size})}>{size}%</button>)}</div><div className="text-size-preview"><strong>Your next great watch.</strong><span>A comfortable size for every story.</span></div><button className="text-button" onClick={()=>change({textScale:125})}>Reset to recommended (125%)</button></section>
  <label className="field-label">THE ATMOSPHERE</label><div className="theme-options">{[{value:'auto',label:'Follow the day',icon:Monitor},{value:'warm',label:'Warm',icon:Sun},{value:'cinema',label:'Cinema',icon:Moon}].map(({value,label,icon:Icon})=><button className={data.settings.theme===value?'selected':''} key={value} onClick={()=>change({theme:value as Settings['theme']})}><Icon size={21}/><span>{label}</span>{data.settings.theme===value&&<Check size={13}/>}</button>)}</div><div className="form-row"><label>Cinema begins<select value={data.settings.cinemaStart} onChange={e=>change({cinemaStart:Number(e.target.value)})}>{Array.from({length:24},(_,h)=><option value={h} key={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label><label>Warm returns<select value={data.settings.cinemaEnd} onChange={e=>change({cinemaEnd:Number(e.target.value)})}>{Array.from({length:24},(_,h)=><option value={h} key={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label></div>
  <label className="field-label">YOUR LIBRARY</label><button className="folder-setting" onClick={()=>run(()=>api?.chooseRoot())}><FolderOpen size={22}/><span>{data.root||'Choose a folder'}<small>Choose a different local library</small></span></button>
  <section className="hidden-videos"><h3>Hidden videos <span>{hidden.length}</span></h3><p className="muted">Hidden from Astra. Their files stay exactly where they are.</p>{hidden.map(item=><div className="hidden-row" key={item.id}><span>{item.title}<small>{item.file}</small></span><IconButton label={`Restore ${item.title}`} onClick={()=>run(()=>api?.hide(item.id,false))}><Undo2 size={18}/></IconButton></div>)}{!hidden.length&&<p className="muted">No hidden videos.</p>}</section>
  <p className="muted">Embedded captions and local subtitle files are supported. Offline automatic caption generation remains planned for a later release.</p><p className="version">ASTRA {version} · MADE FOR SLOW EVENINGS</p>
 </div>;
}
