import {useEffect,useRef,useState,type ReactNode,type PointerEvent} from 'react';
import {Check,Eye,EyeOff,MoreHorizontal,Play,Plus,X} from 'lucide-react';
import type {Media} from './types';
export function IconButton({label,children,onClick,active=false,disabled=false}:{label:string;children:ReactNode;onClick?:()=>void;active?:boolean;disabled?:boolean}){return <button type="button" className={`icon-button ${active?'active':''}`} title={label} aria-label={label} disabled={disabled} onClick={onClick}>{children}</button>;}
export function Poster({item,small=false}:{item:Media;small?:boolean}){
 const[failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[item.cover]);const hash=[...item.title].reduce((n,c)=>n+c.charCodeAt(0),0)%6;
 return <div className={`poster poster-${hash} ${small?'poster-small':''}`}>{item.cover&&!failed?<img src={`art://${item.id}/cover?v=${encodeURIComponent(item.cover)}`} alt="" loading="lazy" onError={()=>setFailed(true)}/>:<div className="poster-art"><span className="poster-edition">THE PERSONAL COLLECTION</span><div className="poster-orbit"/><span className="poster-type">{item.title}</span><span className="poster-genre">{item.genre}</span></div>}<div className="poster-glare"/>{item.watched&&<span className="watched-badge" title="Watched"><Check size={13}/></span>}{!small&&item.position>0&&!item.watched&&item.duration>0&&<div className="poster-progress"><i style={{width:`${Math.min(100,item.position/item.duration*100)}%`}}/></div>}</div>;
}
export function Card({item,onPlay,onQueue,onEdit,pathLabel}:{item:Media;onPlay:(i:Media)=>void;onQueue:(i:Media)=>void;onEdit:(i:Media)=>void;pathLabel?:string}){
 const move=(e:PointerEvent<HTMLButtonElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;e.currentTarget.style.setProperty('--rx',`${(.5-y)*7}deg`);e.currentTarget.style.setProperty('--ry',`${(x-.5)*9}deg`);e.currentTarget.style.setProperty('--gx',`${x*100}%`);e.currentTarget.style.setProperty('--gy',`${y*100}%`);};
 return <article className={`movie-card ${item.missing?'missing':''}`}><button className="poster-button" disabled={item.missing} onPointerMove={move} onPointerLeave={e=>{e.currentTarget.style.setProperty('--rx','0deg');e.currentTarget.style.setProperty('--ry','0deg');}} onClick={()=>onPlay(item)} aria-label={`Play ${item.title}`}><Poster item={item}/><span className="poster-play"><Play size={23} fill="currentColor"/></span></button><div className="card-heading"><h3 title={item.title}>{item.title}</h3><button className="card-menu" onClick={()=>onEdit(item)} aria-label={`Edit ${item.title}`}><MoreHorizontal size={18}/></button></div><div className="card-meta"><span title={pathLabel}>{item.missing?'File unavailable':pathLabel??(item.duration?`${Math.round(item.duration/60)} min`:item.genre)}</span><button onClick={()=>onQueue(item)} disabled={item.missing} aria-label={`Queue ${item.title}`}><Plus size={14}/></button></div></article>;
}
export function Section({title,count,collapsed,onToggle,children}:{title:string;count:number;collapsed:boolean;onToggle:()=>void;children:ReactNode}){return <section className="shelf"><div className="section-heading"><h2>{title}<span>{count}</span></h2><span className="shelf-line"/><button className="icon-button" aria-label={`${collapsed?'Expand':'Collapse'} ${title}`} aria-expanded={!collapsed} onClick={onToggle}>{collapsed?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{!collapsed&&children}</section>;}
export function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.querySelector<HTMLElement>('button,input')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.stopPropagation();onClose();}if(e.key!=='Tab')return;const nodes=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};const el=ref.current;el?.addEventListener('keydown',key);return()=>{el?.removeEventListener('keydown',key);previous?.focus();};},[onClose]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" ref={ref}><header><span className="eyebrow">ASTRA / YOUR COLLECTION</span><IconButton label="Close dialog" onClick={onClose}><X size={19}/></IconButton></header><h2 id="modal-title">{title}</h2>{children}</div></div>;
}
export function Empty({title,body,icon,action}:{title:string;body:string;icon:ReactNode;action?:ReactNode}){return <div className="empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{body}</p>{action}<span className="empty-caption">LOCAL FILES. LIMITLESS REWATCHES.</span></div>;}
